
name: CI

on:
  push:

jobs:
  push_to_registry:
    name: Push Docker 
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
    
      - name: Cross
        uses: actions/checkout@v3
      
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB.TOKEN }}
      - run: docker build -t ghcr.io/razorxzxc/1:latest . /python
      - run: docker push ghcr.io/razorxzxc/1:latest .
